---
# Unified inventory for all CI/CD Pipeline Ansible playbooks.
all:
  children:
    catalyst_center:
      hosts:
        catalyst_center:
          ansible_host: localhost
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"

    iosxe:
      vars:
        ansible_network_os: cisco.ios.ios
      hosts:
        Spine01:
          ansible_host: 198.18.128.101
        Spine02:
          ansible_host: 198.18.128.102
        Leaf01:
          ansible_host: 198.18.128.103
        Leaf02:
          ansible_host: 198.18.128.104
        Border01:
          ansible_host: 198.18.128.105
        Border02:
          ansible_host: 198.18.128.106
        dmz1:
          ansible_host: 198.18.128.107
        dmz2:
          ansible_host: 198.18.128.114
        dhcp-server:
          ansible_host: 198.18.128.110

    nxos:
      vars:
        ansible_network_os: cisco.nxos.nxos
      hosts:
        Core-01:
          ansible_host: 198.18.128.108
        Core-02:
          ansible_host: 198.18.128.109

    image_servers:
      hosts:
        swim_image_server:
          ansible_host: "{{ image_server_ip }}"
