---
- name: Apply Device Credentials from settings.json
  hosts: catalyst_center
  gather_facts: false
  vars_files:
    - ../inventory/group_vars/catalyst_center/vault.yml
  module_defaults:
    cisco.dnac.device_credential_workflow_manager: &catc_auth
      dnac_host: "{{ catc_host }}"
      dnac_username: "{{ catc_username }}"
      dnac_password: "{{ catc_password }}"
      dnac_verify: "{{ catc_verify }}"
      dnac_port: "{{ catc_port }}"
      dnac_version: "{{ catc_version }}"
      dnac_debug: "{{ catc_debug }}"
    cisco.dnac.global_credential_info: *catc_auth
    cisco.dnac.netconf_credential: *catc_auth
    cisco.dnac.global_credential_delete: *catc_auth
  pre_tasks:
    - ansible.builtin.import_role:
        name: catc_common
        tasks_from: load_settings
  roles:
    - role: credentials
