---
- name: Template Synchronization from Git using Template Workflow Manager
  hosts: catalyst_center
  gather_facts: true
  vars_files:
    - ../inventory/group_vars/catalyst_center/vault.yml
  vars:
    catc_debug: "{{ lookup('env', 'DEBUG') | default(false) | bool }}"
  module_defaults:
    cisco.dnac.template_workflow_manager:
      dnac_host: "{{ dnac_host }}"
      dnac_username: "{{ catc_username }}"
      dnac_password: "{{ catc_password }}"
      dnac_verify: "{{ dnac_verify }}"
      dnac_port: "{{ dnac_port }}"
      dnac_version: "{{ dnac_version }}"
      dnac_debug: "{{ dnac_debug }}"
      dnac_log_level: "{{ dnac_log_level }}"
      dnac_log: "{{ dnac_log }}"
  roles:
    - role: template_sync
